In [ ]:
# cloning data
!git clone https://github.com/procodingclass/kaggle-movie-data-.git

Cloning into 'kaggle-movie-data-'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.

In [ ]:
# creating dataframe
import pandas as pd
import numpy as np

credits_df = pd.read_csv('/content/kaggle-movie-data-/tmdb_5000_credits.csv')
movies_df = pd.read_csv('/content/kaggle-movie-data-/tmdb_5000_movies.csv')

In [ ]:
# info of credits dataframe
credits_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4802 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [ ]:
# changing col name to merge dataframes
credits_df.rename(columns = {'movie_id' : 'id'} , inplace = True)
credits_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4803 non-null   int64
 1   title   4803 non-null   object
 2   cast    4803 non-null   object
 3   crew    4802 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [ ]:
# merging dataframes
common_df = pd.merge(movies_df , credits_df , on = 'id')
common_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4803 entries, 0 to 4802
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4799 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title_x               4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
 20  title_y               4803 non-null   object
 21  cast                  4803 non-null   object
 22  crew                  4802 non-null   object
dtypes: float64(3), int64(4), object(16)
memory usage: 900.6+ KB

In [ ]:
# dropping columns : cleaning dataset
common_df.drop(['homepage', 'title_x', 'title_y', 'production_companies'] , axis = 1 , inplace = True)
common_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4803 entries, 0 to 4802
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   id                    4803 non-null   int64
 3   keywords              4803 non-null   object
 4   original_language     4803 non-null   object
 5   original_title        4803 non-null   object
 6   overview              4799 non-null   object
 7   popularity            4803 non-null   float64
 8   production_countries  4803 non-null   object
 9   release_date          4802 non-null   object
 10  revenue               4803 non-null   int64
 11  runtime               4801 non-null   float64
 12  spoken_languages      4803 non-null   object
 13  status                4803 non-null   object
 14  tagline               3959 non-null   object
 15  vote_average          4803 non-null   float64
 16  vote_count            4803 non-null   int64
 17  cast                  4803 non-null   object
 18  crew                  4802 non-null   object
dtypes: float64(3), int64(4), object(12)
memory usage: 750.5+ KB

In [ ]:
common_df.dropna(inplace = True)
common_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3958 entries, 0 to 4801
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                3958 non-null   int64
 1   genres                3958 non-null   object
 2   id                    3958 non-null   int64
 3   keywords              3958 non-null   object
 4   original_language     3958 non-null   object
 5   original_title        3958 non-null   object
 6   overview              3958 non-null   object
 7   popularity            3958 non-null   float64
 8   production_countries  3958 non-null   object
 9   release_date          3958 non-null   object
 10  revenue               3958 non-null   int64
 11  runtime               3958 non-null   float64
 12  spoken_languages      3958 non-null   object
 13  status                3958 non-null   object
 14  tagline               3958 non-null   object
 15  vote_average          3958 non-null   float64
 16  vote_count            3958 non-null   int64
 17  cast                  3958 non-null   object
 18  crew                  3958 non-null   object
dtypes: float64(3), int64(4), object(12)
memory usage: 618.4+ KB

In [ ]:
# calculating weighted average
R = common_df['vote_average']
v = common_df['vote_count']
C = common_df['vote_average'].mean()
m = common_df['vote_count'].quantile(0.9)
print(C , m)
common_df['weighted_rating'] = (R*v + C*m) / (v + m)

6.181859525012634 2101.2000000000007

In [ ]:
# sorting dataframe
common_df.sort_values('weighted_rating' , ascending = False , inplace = True)

In [ ]:
common_df.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,vote_average,vote_count,cast,crew,weighted_rating
1881,25000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name...",278,"[{""id"": 378, ""name"": ""prison""}, {""id"": 417, ""n...",en,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,136.747729,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1994-09-23,28341469,142.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Fear can hold you prisoner. Hope can set you f...,8.5,8205,"[{""cast_id"": 3, ""character"": ""Andy Dufresne"", ...","[{""credit_id"": ""52fe4231c3a36847f800b153"", ""de...",8.027384
662,63000000,"[{""id"": 18, ""name"": ""Drama""}]",550,"[{""id"": 825, ""name"": ""support group""}, {""id"": ...",en,Fight Club,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...",1999-10-15,100853753,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Mischief. Mayhem. Soap.,8.3,9413,"[{""cast_id"": 4, ""character"": ""The Narrator"", ""...","[{""credit_id"": ""55731b8192514111610027d7"", ""de...",7.913465
65,185000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 28, ""name...",155,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight,Batman raises the stakes in his war on crime. ...,187.322927,"[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2008-07-16,1004558444,152.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Why So Serious?,8.2,12002,"[{""cast_id"": 35, ""character"": ""Bruce Wayne"", ""...","[{""credit_id"": ""55a0eb4a925141296b0010f8"", ""de...",7.899322
3232,8000000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 80, ""n...",680,"[{""id"": 396, ""name"": ""transporter""}, {""id"": 14...",en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",121.463076,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1994-10-08,213928762,154.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Just because you are a character doesn't mean ...,8.3,8428,"[{""cast_id"": 2, ""character"": ""Vincent Vega"", ""...","[{""credit_id"": ""52fe4269c3a36847f801caa3"", ""de...",7.877305
96,160000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 53, ""nam...",27205,"[{""id"": 1014, ""name"": ""loss of lover""}, {""id"":...",en,Inception,"Cobb, a skilled thief who commits corporate es...",167.583710,"[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2010-07-14,825532764,148.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Your mind is the scene of the crime.,8.1,13752,"[{""cast_id"": 1, ""character"": ""Dom Cobb"", ""cred...","[{""credit_id"": ""56e8462cc3a368408400354c"", ""de...",7.845768

In [ ]:
# looking at columns : cast, crew, keywords, original title, genres
common_df[['original_title' , 'cast' , 'crew' , 'keywords' , 'genres']].head(3)

,original_title,cast,crew,keywords,genres
1881,The Shawshank Redemption,"[{""cast_id"": 3, ""character"": ""Andy Dufresne"", ...","[{""credit_id"": ""52fe4231c3a36847f800b153"", ""de...","[{""id"": 378, ""name"": ""prison""}, {""id"": 417, ""n...","[{""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name..."
662,Fight Club,"[{""cast_id"": 4, ""character"": ""The Narrator"", ""...","[{""credit_id"": ""55731b8192514111610027d7"", ""de...","[{""id"": 825, ""name"": ""support group""}, {""id"": ...","[{""id"": 18, ""name"": ""Drama""}]"
65,The Dark Knight,"[{""cast_id"": 35, ""character"": ""Bruce Wayne"", ""...","[{""credit_id"": ""55a0eb4a925141296b0010f8"", ""de...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""id"": 18, ""name"": ""Drama""}, {""id"": 28, ""name..."

In [ ]:
# check the datatype of elements
type(common_df.loc[0].at['cast'])

str

In [ ]:
# changing datatype of list
from ast import literal_eval

features = ['cast' , 'crew', 'keywords', 'genres']

for feature in features:
  common_df[feature] = common_df[feature].apply(literal_eval)

In [ ]:
# testing the datatype again
type(common_df.loc[0].at['cast'])

list

In [ ]:
# printing one element from crew column
common_df.loc[6].at['crew']

[{'credit_id': '52fe46db9251416c91062101',
  'department': 'Production',
  'gender': 2,
  'id': 7879,
  'job': 'Executive Producer',
  'name': 'John Lasseter'},
 {'credit_id': '52fe46db9251416c910620e3',
  'department': 'Writing',
  'gender': 2,
  'id': 38748,
  'job': 'Novel',
  'name': 'Jacob Grimm'},
 {'credit_id': '52fe46db9251416c910620dd',
  'department': 'Writing',
  'gender': 2,
  'id': 5448,
  'job': 'Novel',
  'name': 'Wilhelm Grimm'},
 {'credit_id': '572bc6f992514138820000d3',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 8020,
  'job': 'Animation Supervisor',
  'name': 'John Kahrs'},
 {'credit_id': '572bc5d3c3a3687ffd0000a3',
  'department': 'Art',
  'gender': 0,
  'id': 12072,
  'job': 'Production Design',
  'name': 'Douglas Rogers'},
 {'credit_id': '52fe46db9251416c910620e9',
  'department': 'Sound',
  'gender': 2,
  'id': 15813,
  'job': 'Original Music Composer',
  'name': 'Alan Menken'},
 {'credit_id': '572bc54cc3a36801330000b9',
  'department': 'Sound',
  'gender': 2,
  'id': 15813,
  'job': 'Songs',
  'name': 'Alan Menken'},
 {'credit_id': '572bc4c3c3a3687ff90000c2',
  'department': 'Writing',
  'gender': 2,
  'id': 15892,
  'job': 'Screenplay',
  'name': 'Dan Fogelman'},
 {'credit_id': '52fe46db9251416c910620fb',
  'department': 'Production',
  'gender': 0,
  'id': 56612,
  'job': 'Producer',
  'name': 'Roy Conli'},
 {'credit_id': '572bc61492514138900000e1',
  'department': 'Writing',
  'gender': 0,
  'id': 61414,
  'job': 'Story',
  'name': 'Mark Kennedy'},
 {'credit_id': '572bc5c292514138850000c2',
  'department': 'Art',
  'gender': 0,
  'id': 61422,
  'job': 'Co-Art Director',
  'name': 'Dan Cooper'},
 {'credit_id': '572bc56ec3a368013d0000be',
  'department': 'Editing',
  'gender': 2,
  'id': 61958,
  'job': 'Editor',
  'name': 'Tim Mertens'},
 {'credit_id': '572bd492c3a368012f000352',
  'department': 'Sound',
  'gender': 2,
  'id': 65644,
  'job': 'Original Music Composer',
  'name': 'Kevin Kliesch'},
 {'credit_id': '52fe46db9251416c910620bf',
  'department': 'Directing',
  'gender': 2,
  'id': 76595,
  'job': 'Director',
  'name': 'Byron Howard'},
 {'credit_id': '572bd502c3a3687ff90002fd',
  'department': 'Sound',
  'gender': 2,
  'id': 83091,
  'job': 'Sound Re-Recording Mixer',
  'name': 'Dean A. Zupancic'},
 {'credit_id': '572bd4ee92514138940002b8',
  'department': 'Sound',
  'gender': 0,
  'id': 112609,
  'job': 'Sound Re-Recording Mixer',
  'name': 'David E. Fluhr'},
 {'credit_id': '52fe46db9251416c910620ad',
  'department': 'Directing',
  'gender': 2,
  'id': 121830,
  'job': 'Director',
  'name': 'Nathan Greno'},
 {'credit_id': '52fe46db9251416c91062119',
  'department': 'Production',
  'gender': 0,
  'id': 137198,
  'job': 'Casting',
  'name': 'Jamie Sparer Roberts'},
 {'credit_id': '52fe46db9251416c91062107',
  'department': 'Production',
  'gender': 0,
  'id': 139474,
  'job': 'Executive Producer',
  'name': 'Glen Keane'},
 {'credit_id': '572bc6ee92514138850000ec',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 139474,
  'job': 'Animation Supervisor',
  'name': 'Glen Keane'},
 {'credit_id': '572bcbb3c3a3680133000154',
  'department': 'Writing',
  'gender': 0,
  'id': 139474,
  'job': 'Characters',
  'name': 'Glen Keane'},
 {'credit_id': '572bd4cb92514138880002d5',
  'department': 'Crew',
  'gender': 0,
  'id': 928608,
  'job': 'Post Production Supervisor',
  'name': 'Brent W. Hall'},
 {'credit_id': '572bc96c92514138880000f8',
  'department': 'Crew',
  'gender': 0,
  'id': 953331,
  'job': 'Executive Music Producer',
  'name': 'Chris Montan'},
 {'credit_id': '572bc544c3a368012f0000d1',
  'department': 'Sound',
  'gender': 0,
  'id': 1017262,
  'job': 'Songs',
  'name': 'Glenn Slater'},
 {'credit_id': '572bca45c3a3680133000136',
  'department': 'Crew',
  'gender': 0,
  'id': 1123657,
  'job': 'Supervising Animator',
  'name': 'Lino DiSalvo'},
 {'credit_id': '572bc589c3a368012f0000dd',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1210381,
  'job': 'Visual Effects Supervisor',
  'name': 'Steve Goldberg'},
 {'credit_id': '572bc70a92514138850000f0',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1281387,
  'job': 'Animation Supervisor',
  'name': 'Clay Kaytis'},
 {'credit_id': '572bc97ec3a3687ff7000114',
  'department': 'Sound',
  'gender': 0,
  'id': 1291315,
  'job': 'Music Supervisor',
  'name': 'Tom MacDougall'},
 {'credit_id': '572bd51792514138960002cb',
  'department': 'Sound',
  'gender': 1,
  'id': 1367494,
  'job': 'Sound Editor',
  'name': 'Ai-Ling Lee'},
 {'credit_id': '572bcd14c3a3687ff7000184',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1368856,
  'job': 'Visual Development',
  'name': 'Laurent Ben-Mimoun'},
 {'credit_id': '572bca0e925141388e00013a',
  'department': 'Production',
  'gender': 0,
  'id': 1381896,
  'job': 'Production Supervisor',
  'name': 'Tim Pauer'},
 {'credit_id': '572bd539925141388a0002e3',
  'department': 'Sound',
  'gender': 0,
  'id': 1408301,
  'job': 'Sound Editor',
  'name': 'Jason W. Jennings'},
 {'credit_id': '572bc9fb925141388500012e',
  'department': 'Sound',
  'gender': 2,
  'id': 1424167,
  'job': 'Sound Designer',
  'name': 'Cameron Frankley'},
 {'credit_id': '550d7f219251414695005afd',
  'department': 'Production',
  'gender': 0,
  'id': 1443211,
  'job': 'Associate Producer',
  'name': 'Aimee Scribner'},
 {'credit_id': '5543e0cf925141586d0026f3',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1447400,
  'job': 'Visual Development',
  'name': 'James Finn'},
 {'credit_id': '5542343f9251413d6d003a7b',
  'department': 'Directing',
  'gender': 0,
  'id': 1447483,
  'job': 'Layout',
  'name': 'Rick Moore'},
 {'credit_id': '5548cc21c3a368787e0020f1',
  'department': 'Directing',
  'gender': 0,
  'id': 1447497,
  'job': 'Layout',
  'name': 'Merrick Rustia'},
 {'credit_id': '572bcbbec3a368012f000196',
  'department': 'Writing',
  'gender': 0,
  'id': 1447499,
  'job': 'Characters',
  'name': 'Bill Schwab'},
 {'credit_id': '572bd2eec3a368013d000275',
  'department': 'Directing',
  'gender': 0,
  'id': 1451279,
  'job': 'Layout',
  'name': 'Doug Walker'},
 {'credit_id': '572bce6d92514138960001e0',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1461361,
  'job': 'Visual Development',
  'name': 'Lorelay Bove'},
 {'credit_id': '572bd151c3a368012c000248',
  'department': 'Directing',
  'gender': 0,
  'id': 1461363,
  'job': 'Layout',
  'name': 'Brian Kesinger'},
 {'credit_id': '572bcbcc925141388200012d',
  'department': 'Writing',
  'gender': 0,
  'id': 1461364,
  'job': 'Characters',
  'name': 'Shiyoon Kim'},
 {'credit_id': '572bd1439251413882000243',
  'department': 'Directing',
  'gender': 0,
  'id': 1461397,
  'job': 'Layout',
  'name': 'Daniel Hu'},
 {'credit_id': '572bce8f92514138960001e3',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1461399,
  'job': 'Visual Development',
  'name': 'Lisa Keene'},
 {'credit_id': '572bc95a925141388e000121',
  'department': 'Production',
  'gender': 0,
  'id': 1464355,
  'job': 'Executive In Charge Of Post Production',
  'name': 'Bérénice Robinson'},
 {'credit_id': '572bca20925141389600012f',
  'department': 'Production',
  'gender': 0,
  'id': 1464361,
  'job': 'Production Supervisor',
  'name': 'Jennifer Christine Vera'},
 {'credit_id': '572bc8cac3a368012f00013e',
  'department': 'Lighting',
  'gender': 0,
  'id': 1470064,
  'job': 'Lighting Supervisor',
  'name': 'Josh Staub'},
 {'credit_id': '572bc5a0c3a3687ff70000b7',
  'department': 'Art',
  'gender': 2,
  'id': 1552863,
  'job': 'Art Direction',
  'name': 'David Goetz'},
 {'credit_id': '572bcf0fc3a368012f000270',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1552865,
  'job': 'Visual Development',
  'name': 'Kent Melton'},
 {'credit_id': '572bc943925141389400010e',
  'department': 'Production',
  'gender': 0,
  'id': 1554457,
  'job': 'Production Manager',
  'name': 'Doeri Welch Greiner'},
 {'credit_id': '572bd1979251413882000254',
  'department': 'Directing',
  'gender': 0,
  'id': 1578645,
  'job': 'Layout',
  'name': 'John Murrah'},
 {'credit_id': '572bc62fc3a3687ff90000e9',
  'department': 'Directing',
  'gender': 2,
  'id': 1615775,
  'job': 'Layout',
  'name': 'Scott Beattie'},
 {'credit_id': '572bc6aec3a3687ffd0000ca',
  'department': 'Crew',
  'gender': 2,
  'id': 1615776,
  'job': 'Technical Supervisor',
  'name': 'Mark Hammel'},
 {'credit_id': '572bc76b92514138850000f8',
  'department': 'Lighting',
  'gender': 2,
  'id': 1615777,
  'job': 'Lighting Supervisor',
  'name': 'Richard E. Lehmann'},
 {'credit_id': '572bc7dc92514138940000ef',
  'department': 'Lighting',
  'gender': 2,
  'id': 1615778,
  'job': 'Lighting Supervisor',
  'name': 'Robert L. Miles'},
 {'credit_id': '572bc813c3a3687ff9000136',
  'department': 'Lighting',
  'gender': 2,
  'id': 1615779,
  'job': 'Lighting Supervisor',
  'name': 'Brian Leach'},
 {'credit_id': '572bc84e925141388e00010c',
  'department': 'Lighting',
  'gender': 0,
  'id': 1615780,
  'job': 'Lighting Supervisor',
  'name': 'Alessandro Jacomini'},
 {'credit_id': '572bc88dc3a368013d0000fd',
  'department': 'Lighting',
  'gender': 2,
  'id': 1615781,
  'job': 'Lighting Supervisor',
  'name': 'Ernest J. Petti'},
 {'credit_id': '572bc8e3c3a3680140000100',
  'department': 'Lighting',
  'gender': 0,
  'id': 1615782,
  'job': 'Lighting Supervisor',
  'name': 'Chris Springfield'},
 {'credit_id': '572bcbd8c3a368013300015c',
  'department': 'Writing',
  'gender': 0,
  'id': 1615783,
  'job': 'Characters',
  'name': 'Jin Kim'},
 {'credit_id': '572bccae9251413885000196',
  'department': 'Visual Effects',
  'gender': 1,
  'id': 1615784,
  'job': 'Visual Development',
  'name': 'Lauren Airriess'},
 {'credit_id': '572bcd5cc3a368014000019e',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1615785,
  'job': 'Visual Development',
  'name': 'Justin Cram'},
 {'credit_id': '572bcdb0925141388e0001e1',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1615786,
  'job': 'Visual Development',
  'name': 'Gustaf Aspegren'},
 {'credit_id': '572bcea7c3a368013d0001e4',
  'department': 'Visual Effects',
  'gender': 1,
  'id': 1615787,
  'job': 'Visual Development',
  'name': 'Claire Keane'},
 {'credit_id': '572bcf05c3a368012c0001f6',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1615788,
  'job': 'Visual Development',
  'name': 'Craig Mullins'},
 {'credit_id': '572bcf87c3a368012c000219',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1615789,
  'job': 'Visual Development',
  'name': 'Scott Watanabe'},
 {'credit_id': '572bcf979251413894000216',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1615790,
  'job': 'Visual Development',
  'name': 'Victoria Ying'},
 {'credit_id': '572bd038925141388800021a',
  'department': 'Directing',
  'gender': 0,
  'id': 1615791,
  'job': 'Layout',
  'name': 'Cory Rocco Florimonte'},
 {'credit_id': '572bd093c3a3687ff700022f',
  'department': 'Directing',
  'gender': 2,
  'id': 1615792,
  'job': 'Layout',
  'name': 'Allen Blaisdell'},
 {'credit_id': '572bd0c9c3a368012f0002af',
  'department': 'Directing',
  'gender': 2,
  'id': 1615793,
  'job': 'Layout',
  'name': 'Rob Dressel'},
 {'credit_id': '572bd11a925141388e000264',
  'department': 'Directing',
  'gender': 0,
  'id': 1615794,
  'job': 'Layout',
  'name': 'Todd Allen Erickson'},
 {'credit_id': '572bd15d925141388800024b',
  'department': 'Directing',
  'gender': 0,
  'id': 1615795,
  'job': 'Layout',
  'name': 'Terry Moews'},
 {'credit_id': '572bd1b5c3a3687ff7000271',
  'department': 'Directing',
  'gender': 2,
  'id': 1615796,
  'job': 'Layout',
  'name': 'Christopher K. Poplin'},
 {'credit_id': '572bd2069251413888000267',
  'department': 'Directing',
  'gender': 2,
  'id': 1615797,
  'job': 'Layout',
  'name': 'Wally Schaab'},
 {'credit_id': '572bd2ccc3a368012c00026c',
  'department': 'Directing',
  'gender': 0,
  'id': 1615799,
  'job': 'Layout',
  'name': 'Richard Turner'},
 {'credit_id': '572bd309925141388800027f',
  'department': 'Directing',
  'gender': 0,
  'id': 1615800,
  'job': 'Layout',
  'name': 'David Wainstain'},
 {'credit_id': '572bd3f9925141388200029f',
  'department': 'Crew',
  'gender': 2,
  'id': 1615802,
  'job': 'Software Engineer',
  'name': 'Brent Burley'},
 {'credit_id': '572bd403c3a36801400002ac',
  'department': 'Crew',
  'gender': 2,
  'id': 1615803,
  'job': 'Software Engineer',
  'name': 'Brendan Duncan'},
 {'credit_id': '58ac80fa92514158f60148f7',
  'department': 'Crew',
  'gender': 0,
  'id': 1763017,
  'job': 'Supervising Animator',
  'name': 'Mark Mitchell'}]

In [ ]:
# adding director column in dataframe
def get_director(crew):
  for crew_member in crew:
    if crew_member['job']  ==  'Director':
      return crew_member['name']

  return np.nan

common_df['director'] = common_df['crew'].apply(get_director)

In [ ]:
# print the title and director column
common_df[['original_title' , 'director']].head()

                original_title           director
1881  The Shawshank Redemption     Frank Darabont
662                 Fight Club      David Fincher
65             The Dark Knight  Christopher Nolan
3232              Pulp Fiction  Quentin Tarantino
96                   Inception  Christopher Nolan

In [ ]:
# printing first element in cast column
common_df.loc[0].at['cast']

[{'cast_id': 242,
  'character': 'Jake Sully',
  'credit_id': '5602a8a7c3a3685532001c9a',
  'gender': 2,
  'id': 65731,
  'name': 'Sam Worthington',
  'order': 0},
 {'cast_id': 3,
  'character': 'Neytiri',
  'credit_id': '52fe48009251416c750ac9cb',
  'gender': 1,
  'id': 8691,
  'name': 'Zoe Saldana',
  'order': 1},
 {'cast_id': 25,
  'character': 'Dr. Grace Augustine',
  'credit_id': '52fe48009251416c750aca39',
  'gender': 1,
  'id': 10205,
  'name': 'Sigourney Weaver',
  'order': 2},
 {'cast_id': 4,
  'character': 'Col. Quaritch',
  'credit_id': '52fe48009251416c750ac9cf',
  'gender': 2,
  'id': 32747,
  'name': 'Stephen Lang',
  'order': 3},
 {'cast_id': 5,
  'character': 'Trudy Chacon',
  'credit_id': '52fe48009251416c750ac9d3',
  'gender': 1,
  'id': 17647,
  'name': 'Michelle Rodriguez',
  'order': 4},
 {'cast_id': 8,
  'character': 'Selfridge',
  'credit_id': '52fe48009251416c750ac9e1',
  'gender': 2,
  'id': 1771,
  'name': 'Giovanni Ribisi',
  'order': 5},
 {'cast_id': 7,
  'character': 'Norm Spellman',
  'credit_id': '52fe48009251416c750ac9dd',
  'gender': 2,
  'id': 59231,
  'name': 'Joel David Moore',
  'order': 6},
 {'cast_id': 9,
  'character': 'Moat',
  'credit_id': '52fe48009251416c750ac9e5',
  'gender': 1,
  'id': 30485,
  'name': 'CCH Pounder',
  'order': 7},
 {'cast_id': 11,
  'character': 'Eytukan',
  'credit_id': '52fe48009251416c750ac9ed',
  'gender': 2,
  'id': 15853,
  'name': 'Wes Studi',
  'order': 8},
 {'cast_id': 10,
  'character': "Tsu'Tey",
  'credit_id': '52fe48009251416c750ac9e9',
  'gender': 2,
  'id': 10964,
  'name': 'Laz Alonso',
  'order': 9},
 {'cast_id': 12,
  'character': 'Dr. Max Patel',
  'credit_id': '52fe48009251416c750ac9f1',
  'gender': 2,
  'id': 95697,
  'name': 'Dileep Rao',
  'order': 10},
 {'cast_id': 13,
  'character': 'Lyle Wainfleet',
  'credit_id': '52fe48009251416c750ac9f5',
  'gender': 2,
  'id': 98215,
  'name': 'Matt Gerald',
  'order': 11},
 {'cast_id': 32,
  'character': 'Private Fike',
  'credit_id': '52fe48009251416c750aca5b',
  'gender': 2,
  'id': 154153,
  'name': 'Sean Anthony Moran',
  'order': 12},
 {'cast_id': 33,
  'character': 'Cryo Vault Med Tech',
  'credit_id': '52fe48009251416c750aca5f',
  'gender': 2,
  'id': 397312,
  'name': 'Jason Whyte',
  'order': 13},
 {'cast_id': 34,
  'character': 'Venture Star Crew Chief',
  'credit_id': '52fe48009251416c750aca63',
  'gender': 2,
  'id': 42317,
  'name': 'Scott Lawrence',
  'order': 14},
 {'cast_id': 35,
  'character': 'Lock Up Trooper',
  'credit_id': '52fe48009251416c750aca67',
  'gender': 2,
  'id': 986734,
  'name': 'Kelly Kilgour',
  'order': 15},
 {'cast_id': 36,
  'character': 'Shuttle Pilot',
  'credit_id': '52fe48009251416c750aca6b',
  'gender': 0,
  'id': 1207227,
  'name': 'James Patrick Pitt',
  'order': 16},
 {'cast_id': 37,
  'character': 'Shuttle Co-Pilot',
  'credit_id': '52fe48009251416c750aca6f',
  'gender': 0,
  'id': 1180936,
  'name': 'Sean Patrick Murphy',
  'order': 17},
 {'cast_id': 38,
  'character': 'Shuttle Crew Chief',
  'credit_id': '52fe48009251416c750aca73',
  'gender': 2,
  'id': 1019578,
  'name': 'Peter Dillon',
  'order': 18},
 {'cast_id': 39,
  'character': 'Tractor Operator / Troupe',
  'credit_id': '52fe48009251416c750aca77',
  'gender': 0,
  'id': 91443,
  'name': 'Kevin Dorman',
  'order': 19},
 {'cast_id': 40,
  'character': 'Dragon Gunship Pilot',
  'credit_id': '52fe48009251416c750aca7b',
  'gender': 2,
  'id': 173391,
  'name': 'Kelson Henderson',
  'order': 20},
 {'cast_id': 41,
  'character': 'Dragon Gunship Gunner',
  'credit_id': '52fe48009251416c750aca7f',
  'gender': 0,
  'id': 1207236,
  'name': 'David Van Horn',
  'order': 21},
 {'cast_id': 42,
  'character': 'Dragon Gunship Navigator',
  'credit_id': '52fe48009251416c750aca83',
  'gender': 0,
  'id': 215913,
  'name': 'Jacob Tomuri',
  'order': 22},
 {'cast_id': 43,
  'character': 'Suit #1',
  'credit_id': '52fe48009251416c750aca87',
  'gender': 0,
  'id': 143206,
  'name': 'Michael Blain-Rozgay',
  'order': 23},
 {'cast_id': 44,
  'character': 'Suit #2',
  'credit_id': '52fe48009251416c750aca8b',
  'gender': 2,
  'id': 169676,
  'name': 'Jon Curry',
  'order': 24},
 {'cast_id': 46,
  'character': 'Ambient Room Tech',
  'credit_id': '52fe48009251416c750aca8f',
  'gender': 0,
  'id': 1048610,
  'name': 'Luke Hawker',
  'order': 25},
 {'cast_id': 47,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48009251416c750aca93',
  'gender': 0,
  'id': 42288,
  'name': 'Woody Schultz',
  'order': 26},
 {'cast_id': 48,
  'character': 'Horse Clan Leader',
  'credit_id': '52fe48009251416c750aca97',
  'gender': 2,
  'id': 68278,
  'name': 'Peter Mensah',
  'order': 27},
 {'cast_id': 49,
  'character': 'Link Room Tech',
  'credit_id': '52fe48009251416c750aca9b',
  'gender': 0,
  'id': 1207247,
  'name': 'Sonia Yee',
  'order': 28},
 {'cast_id': 50,
  'character': 'Basketball Avatar / Troupe',
  'credit_id': '52fe48009251416c750aca9f',
  'gender': 1,
  'id': 1207248,
  'name': 'Jahnel Curfman',
  'order': 29},
 {'cast_id': 51,
  'character': 'Basketball Avatar',
  'credit_id': '52fe48009251416c750acaa3',
  'gender': 0,
  'id': 89714,
  'name': 'Ilram Choi',
  'order': 30},
 {'cast_id': 52,
  'character': "Na'vi Child",
  'credit_id': '52fe48009251416c750acaa7',
  'gender': 0,
  'id': 1207249,
  'name': 'Kyla Warren',
  'order': 31},
 {'cast_id': 53,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaab',
  'gender': 0,
  'id': 1207250,
  'name': 'Lisa Roumain',
  'order': 32},
 {'cast_id': 54,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaaf',
  'gender': 1,
  'id': 83105,
  'name': 'Debra Wilson',
  'order': 33},
 {'cast_id': 57,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabb',
  'gender': 0,
  'id': 1207253,
  'name': 'Chris Mala',
  'order': 34},
 {'cast_id': 55,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab3',
  'gender': 0,
  'id': 1207251,
  'name': 'Taylor Kibby',
  'order': 35},
 {'cast_id': 56,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab7',
  'gender': 0,
  'id': 1207252,
  'name': 'Jodie Landau',
  'order': 36},
 {'cast_id': 58,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabf',
  'gender': 0,
  'id': 1207254,
  'name': 'Julie Lamm',
  'order': 37},
 {'cast_id': 59,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac3',
  'gender': 0,
  'id': 1207257,
  'name': 'Cullen B. Madden',
  'order': 38},
 {'cast_id': 60,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac7',
  'gender': 0,
  'id': 1207259,
  'name': 'Joseph Brady Madden',
  'order': 39},
 {'cast_id': 61,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacb',
  'gender': 0,
  'id': 1207262,
  'name': 'Frankie Torres',
  'order': 40},
 {'cast_id': 62,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacf',
  'gender': 1,
  'id': 1158600,
  'name': 'Austin Wilson',
  'order': 41},
 {'cast_id': 63,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad3',
  'gender': 1,
  'id': 983705,
  'name': 'Sara Wilson',
  'order': 42},
 {'cast_id': 64,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad7',
  'gender': 0,
  'id': 1207263,
  'name': 'Tamica Washington-Miller',
  'order': 43},
 {'cast_id': 65,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadb',
  'gender': 1,
  'id': 1145098,
  'name': 'Lucy Briant',
  'order': 44},
 {'cast_id': 66,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadf',
  'gender': 2,
  'id': 33305,
  'name': 'Nathan Meister',
  'order': 45},
 {'cast_id': 67,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae3',
  'gender': 0,
  'id': 1207264,
  'name': 'Gerry Blair',
  'order': 46},
 {'cast_id': 68,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae7',
  'gender': 2,
  'id': 33311,
  'name': 'Matthew Chamberlain',
  'order': 47},
 {'cast_id': 69,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaeb',
  'gender': 0,
  'id': 1207265,
  'name': 'Paul Yates',
  'order': 48},
 {'cast_id': 70,
  'character': 'Op Center Duty Officer',
  'credit_id': '52fe48019251416c750acaef',
  'gender': 0,
  'id': 1207266,
  'name': 'Wray Wilson',
  'order': 49},
 {'cast_id': 71,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaf3',
  'gender': 2,
  'id': 54492,
  'name': 'James Gaylyn',
  'order': 50},
 {'cast_id': 72,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaf7',
  'gender': 0,
  'id': 1207267,
  'name': 'Melvin Leno Clark III',
  'order': 51},
 {'cast_id': 73,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acafb',
  'gender': 0,
  'id': 1207268,
  'name': 'Carvon Futrell',
  'order': 52},
 {'cast_id': 74,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaff',
  'gender': 0,
  'id': 1207269,
  'name': 'Brandon Jelkes',
  'order': 53},
 {'cast_id': 75,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb03',
  'gender': 0,
  'id': 1207270,
  'name': 'Micah Moch',
  'order': 54},
 {'cast_id': 76,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb07',
  'gender': 0,
  'id': 1207271,
  'name': 'Hanniyah Muhammad',
  'order': 55},
 {'cast_id': 77,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0b',
  'gender': 0,
  'id': 1207272,
  'name': 'Christopher Nolen',
  'order': 56},
 {'cast_id': 78,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0f',
  'gender': 0,
  'id': 1207273,
  'name': 'Christa Oliver',
  'order': 57},
 {'cast_id': 79,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb13',
  'gender': 0,
  'id': 1207274,
  'name': 'April Marie Thomas',
  'order': 58},
 {'cast_id': 80,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb17',
  'gender': 0,
  'id': 1207275,
  'name': 'Bravita A. Threatt',
  'order': 59},
 {'cast_id': 81,
  'character': 'Mining Chief (uncredited)',
  'credit_id': '52fe48019251416c750acb1b',
  'gender': 0,
  'id': 1207276,
  'name': 'Colin Bleasdale',
  'order': 60},
 {'cast_id': 82,
  'character': 'Veteran Miner (uncredited)',
  'credit_id': '52fe48019251416c750acb1f',
  'gender': 0,
  'id': 107969,
  'name': 'Mike Bodnar',
  'order': 61},
 {'cast_id': 83,
  'character': 'Richard (uncredited)',
  'credit_id': '52fe48019251416c750acb23',
  'gender': 0,
  'id': 1207278,
  'name': 'Matt Clayton',
  'order': 62},
 {'cast_id': 84,
  'character': "Nav'i (uncredited)",
  'credit_id': '52fe48019251416c750acb27',
  'gender': 1,
  'id': 147898,
  'name': 'Nicole Dionne',
  'order': 63},
 {'cast_id': 85,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2b',
  'gender': 0,
  'id': 1207280,
  'name': 'Jamie Harrison',
  'order': 64},
 {'cast_id': 86,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2f',
  'gender': 0,
  'id': 1207281,
  'name': 'Allan Henry',
  'order': 65},
 {'cast_id': 87,
  'character': 'Ground Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb33',
  'gender': 2,
  'id': 1207282,
  'name': 'Anthony Ingruber',
  'order': 66},
 {'cast_id': 88,
  'character': 'Flight Crew Mechanic (uncredited)',
  'credit_id': '52fe48019251416c750acb37',
  'gender': 0,
  'id': 1207283,
  'name': 'Ashley Jeffery',
  'order': 67},
 {'cast_id': 14,
  'character': 'Samson Pilot',
  'credit_id': '52fe48009251416c750ac9f9',
  'gender': 0,
  'id': 98216,
  'name': 'Dean Knowsley',
  'order': 68},
 {'cast_id': 89,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb3b',
  'gender': 0,
  'id': 1201399,
  'name': 'Joseph Mika-Hunt',
  'order': 69},
 {'cast_id': 90,
  'character': 'Banshee (uncredited)',
  'credit_id': '52fe48019251416c750acb3f',
  'gender': 0,
  'id': 236696,
  'name': 'Terry Notary',
  'order': 70},
 {'cast_id': 91,
  'character': 'Soldier (uncredited)',
  'credit_id': '52fe48019251416c750acb43',
  'gender': 0,
  'id': 1207287,
  'name': 'Kai Pantano',
  'order': 71},
 {'cast_id': 92,
  'character': 'Blast Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb47',
  'gender': 0,
  'id': 1207288,
  'name': 'Logan Pithyou',
  'order': 72},
 {'cast_id': 93,
  'character': 'Vindum Raah (uncredited)',
  'credit_id': '52fe48019251416c750acb4b',
  'gender': 0,
  'id': 1207289,
  'name': 'Stuart Pollock',
  'order': 73},
 {'cast_id': 94,
  'character': 'Hero (uncredited)',
  'credit_id': '52fe48019251416c750acb4f',
  'gender': 0,
  'id': 584868,
  'name': 'Raja',
  'order': 74},
 {'cast_id': 95,
  'character': 'Ops Centreworker (uncredited)',
  'credit_id': '52fe48019251416c750acb53',
  'gender': 0,
  'id': 1207290,
  'name': 'Gareth Ruck',
  'order': 75},
 {'cast_id': 96,
  'character': 'Engineer (uncredited)',
  'credit_id': '52fe48019251416c750acb57',
  'gender': 0,
  'id': 1062463,
  'name': 'Rhian Sheehan',
  'order': 76},
 {'cast_id': 97,
  'character': "Col. Quaritch's Mech Suit (uncredited)",
  'credit_id': '52fe48019251416c750acb5b',
  'gender': 0,
  'id': 60656,
  'name': 'T. J. Storm',
  'order': 77},
 {'cast_id': 98,
  'character': 'Female Marine (uncredited)',
  'credit_id': '52fe48019251416c750acb5f',
  'gender': 0,
  'id': 1207291,
  'name': 'Jodie Taylor',
  'order': 78},
 {'cast_id': 99,
  'character': 'Ikran Clan Leader (uncredited)',
  'credit_id': '52fe48019251416c750acb63',
  'gender': 1,
  'id': 1186027,
  'name': 'Alicia Vela-Bailey',
  'order': 79},
 {'cast_id': 100,
  'character': 'Geologist (uncredited)',
  'credit_id': '52fe48019251416c750acb67',
  'gender': 0,
  'id': 1207292,
  'name': 'Richard Whiteside',
  'order': 80},
 {'cast_id': 101,
  'character': "Na'vi (uncredited)",
  'credit_id': '52fe48019251416c750acb6b',
  'gender': 0,
  'id': 103259,
  'name': 'Nikie Zambo',
  'order': 81},
 {'cast_id': 102,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48019251416c750acb6f',
  'gender': 1,
  'id': 42286,
  'name': 'Julene Renee',
  'order': 82}]

In [ ]:
# printing first element in keywords column
common_df.loc[0].at['keywords']

[{'id': 1463, 'name': 'culture clash'},
 {'id': 2964, 'name': 'future'},
 {'id': 3386, 'name': 'space war'},
 {'id': 3388, 'name': 'space colony'},
 {'id': 3679, 'name': 'society'},
 {'id': 3801, 'name': 'space travel'},
 {'id': 9685, 'name': 'futuristic'},
 {'id': 9840, 'name': 'romance'},
 {'id': 9882, 'name': 'space'},
 {'id': 9951, 'name': 'alien'},
 {'id': 10148, 'name': 'tribe'},
 {'id': 10158, 'name': 'alien planet'},
 {'id': 10987, 'name': 'cgi'},
 {'id': 11399, 'name': 'marine'},
 {'id': 13065, 'name': 'soldier'},
 {'id': 14643, 'name': 'battle'},
 {'id': 14720, 'name': 'love affair'},
 {'id': 165431, 'name': 'anti war'},
 {'id': 193554, 'name': 'power relations'},
 {'id': 206690, 'name': 'mind and soul'},
 {'id': 209714, 'name': '3d'}]

In [ ]:
# printing first element in genres column
common_df.loc[0].at['genres']

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [ ]:
# extracting names
def get_name_list(column_value):
  names_list = []
  if isinstance(column_value , list):
    for element in column_value:
      names_list.append(element['name'])

  return names_list

features = ['cast' , 'keywords' , 'genres']
for feature in features:
  common_df[feature] = common_df[feature].apply(get_name_list)

In [ ]:
# verify the changes
common_df[['cast' , 'keywords' , 'genres' , 'director']].head(3)

,cast,keywords,genres,director
1881,"[Tim Robbins, Morgan Freeman, Bob Gunton, Clan...","[prison, corruption, police brutality, prison ...","[Drama, Crime]",Frank Darabont
662,"[Edward Norton, Brad Pitt, Meat Loaf, Jared Le...","[support group, dual identity, nihilism, rage ...",[Drama],David Fincher
65,"[Christian Bale, Heath Ledger, Aaron Eckhart, ...","[dc comics, crime fighter, secret identity, sc...","[Drama, Action, Crime, Thriller]",Christopher Nolan

In [ ]:
# cleaning data
def clean_data(column_value):
  modified_list = []
  modified_string = ""
  if isinstance(column_value , list):
    for element in column_value:
      modified_string = element.replace(" " , "")
      modified_list.append(modified_string.lower())

    return modified_list

  elif isinstance(column_value , str):
    modified_string = column_value.replace(" " , "")
    return modified_string.lower()

  else:
    return ''

features = ['cast' , 'keywords' , 'genres' , 'director']
for feature in features:
  common_df[feature] = common_df[feature].apply(clean_data)

In [ ]:
# verify the changes
common_df[['cast' , 'keywords' , 'genres' , 'director']].head(3)

,cast,keywords,genres,director
1881,"[timrobbins, morganfreeman, bobgunton, clancyb...","[prison, corruption, policebrutality, prisonce...","[drama, crime]",frankdarabont
662,"[edwardnorton, bradpitt, meatloaf, jaredleto, ...","[supportgroup, dualidentity, nihilism, rageand...",[drama],davidfincher
65,"[christianbale, heathledger, aaroneckhart, mic...","[dccomics, crimefighter, secretidentity, scare...","[drama, action, crime, thriller]",christophernolan

In [ ]:
# try out the .join method
b = ['hello,' , 'how' , 'are' , 'you' , '?']
c = " ".join(b)
print(c)

hello, how are you ?

In [ ]:
# creating soup
def create_soup(x):
   return ' '.join(x['keywords']) + ' ' + ' '.join(x['cast']) + ' ' + x['director'] + ' ' + ' '.join(x['genres'])
common_df['soup'] = common_df.apply(create_soup, axis=1)

In [ ]:
# verifying the output
common_df[['original_title' , 'soup']].head()

,original_title,soup
1881,The Shawshank Redemption,prison corruption policebrutality prisoncell d...
662,Fight Club,supportgroup dualidentity nihilism rageandhate...
65,The Dark Knight,dccomics crimefighter secretidentity scarecrow...
3232,Pulp Fiction,transporter brothel drugdealer boxer massage s...
96,Inception,lossoflover dream kidnapping sleep subconsciou...

In [ ]:
# creating vectors or matrix
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(common_df['soup'])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim2 = cosine_similarity(count_matrix, count_matrix)

In [ ]:
print(cosine_sim2.shape)

(3958, 3958)

In [ ]:
common_df = common_df.reset_index()
indices = pd.Series(common_df.index, index=common_df['original_title'])

In [ ]:
def get_recommendations(title, cosine_sim):
   idx = indices[title]
   sim_scores = list(enumerate(cosine_sim[idx]))
   sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
   sim_scores = sim_scores[1:11]
   movie_indices = [i[0] for i in sim_scores]
   return common_df['original_title'].iloc[movie_indices]

In [ ]:
get_recommendations('Fight Club', cosine_sim2)

16                         Se7en
247                     The Game
248                       Zodiac
386                  World War Z
2665                Full Frontal
1950       Me You and Five Bucks
2152    Amidst the Devil's Wings
3863                     RoboCop
1827                      Alien³
1394                  Salton Sea
Name: original_title, dtype: object

In [ ]:
# converting df to csv
common_df.to_csv('movies.csv')

In [ ]:
# downloading file
from google.colab import files
files.download('movies.csv')